name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          sender: vijay
          from: vijayrachuribiz@gmail.com
          subject: Github Actions job result
          body: file://README.md
          attachments: '[{"path":"README.md"}]'
          to: vijay.rachuri1810@gmail.com