name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
          host: smtp.google.com
          account: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          sender: ${{secrets.EMAIL_USERNAME}}
          from: ${{secrets.EMAIL_USERNAME}}
          to: vijay.rachuri1810@gmail.com
          subject: mail title.
          body: file://README.md
          contentType: text/html
          attachments: file://attachmets.json
