name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests and generate HTML
        run: 
          npm install
          npm test -- --reporter=html > test-report.html
          
      - name: Send email
        if: ${{ always() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          
          from: GitHub workflow@gmail.com
          to: vijay.rachuri1810@gmail.com
          subject: $${{ github.job}} job of $${{ github.repository }}
          body: Please find the Reports attachments
          html-body: ${{ steps.html.outputs.html_body }}
          attachments: README.md
          
          
